### PR TITLE
feat(blog): add October blog flyer, fix blog dates, and display lates…

### LINKED ISSUE #118: Add October Blog Flyer and Display Latest Flyers on first page
October blog link: https://sliitmozilla.psee.io/8aphxa

### PR DESCRIPTION
**Pull request by Vish-p0**
## Add October Blog Flyer and Display Latest Flyers on First Page

This update addresses Issue #118 by improving the blog section in the following ways:

### Key Improvements

- **October Blog Added:**  
  The October blog flyer has been included in the blog list, ensuring all recent content is available to users.

- **Chronological Organization:**  
  Blog posts are now automatically sorted by their publication date in descending order. 

### Screenshot
Image

### Files Updated

- `app/blog/page.tsx`
-  `public/assets/blog9.png`

---
With these changes, users will always see the latest blog flyers and articles first, improving visibility for new content and enhancing the overall user experience.

### CODE REVIEW

File: app/blog/page.tsx [hunk 1]
```diff
@@ -102,22 +102,39 @@ const blogPosts = [
...
+    mediumUrl:
+      "https://medium.com/@infosliitmcc/practical-devops-playbook-for-deploying-academic-projects-1a2f569a05d1",
+  },
 ]
 
+// Sort blogs by date descending (recent first)
+const sortedBlogPosts = [...blogPosts].sort(
+  (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime(),
+)
+
```
Comment (Seniru) [inline app/blog/page.tsx:128]: This is good. But please note that this is not related to the original issue. And most of the time I'd ask you to remove these kind of unrelated changes.
To avoid any wasted efforts in the future, please only change what is requested; and make a separate issue + PR for these additional stuff.
Fine for now but keep this in mind in the future

**Review by Seniru — APPROVED** [review]
